# Generated by Django 3.2.9 on 2021-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='img/announces/'),
        ),
    ]
