# Generated by Django 3.2.9 on 2021-11-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='city',
        ),
    ]
