# Generated by Django 3.2.9 on 2021-11-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20211123_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_announcement', to='announcement.city'),
        ),
    ]
