# Generated by Django 3.2.9 on 2021-11-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_announcement_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade'},
        ),
    ]
