# Generated by Django 3.2.9 on 2021-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_announcement_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type_vacancy',
            field=models.CharField(choices=[('1', 'Emprego'), ('2', 'Estagio')], default='1', max_length=25),
        ),
    ]
