# Generated by Django 3.2.9 on 2021-11-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_announcement_type_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type_vacancy',
            field=models.CharField(choices=[('emprego', 'Emprego'), ('estagio', 'Estagio')], default='1', max_length=25),
        ),
    ]
