# Generated by Django 3.2.9 on 2021-12-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_alter_announcement_type_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
