# Generated by Django 3.2.9 on 2021-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_alter_participateannounce_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participateannounce',
            name='curriculum',
            field=models.FileField(upload_to='users/curriculos/'),
        ),
    ]
