# Generated by Django 3.2.9 on 2021-12-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0012_alter_participateannounce_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
