# Generated by Django 3.2.9 on 2021-12-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0014_alter_announcement_type_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='note',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='prerequisites',
        ),
    ]
