# Generated by Django 3.2.9 on 2021-12-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_city'),
        ('announcement', '0015_auto_20211210_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_announcement', to='authentication.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
