# Generated by Django 3.2.9 on 2021-12-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0017_remove_announcement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participateannounce',
            name='curriculum',
        ),
    ]
