# Generated by Django 3.2.9 on 2021-12-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
