# Generated by Django 3.2.9 on 2021-12-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_solicitation_accept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitation',
            options={'verbose_name': 'Solicitações'},
        ),
    ]
