# Generated by Django 3.2.9 on 2021-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(choices=[('1', 'Você tem uma nova solicitação para avaliar!'), ('2', 'teste')], max_length=150, null=True),
        ),
    ]
