# Generated by Django 3.2.9 on 2021-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
