# Generated by Django 3.2.9 on 2021-12-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211213_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='cnpj',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
