# Generated by Django 3.2.9 on 2021-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum',
            field=models.FileField(max_length=500, null=True, upload_to='users/curriculos/'),
        ),
    ]
