# Generated by Django 3.2.9 on 2022-01-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills_users', to='authentication.Skills'),
        ),
    ]
