
name: deploying changes
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploying changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: 22
          envs: DJANGO_SECRET_KEY
          script: |
            cd Site/Integrador-6-Periodo
            source venv/bin/activate
            git pull
            pip install -r requirements.txt
            python3 manage.py migrate
            systemctl restart gunicorn
            systemctl restart nginx
            


# name: Django CI

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.9]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.9.6
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9.6
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run Tests
#       run: |
#         python manage.py test

#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: 31.220.48.246
#         username: root
#         password: Jefersonqueiroga123#
#         port: 22
#         script: whoami

