name: Django Integracao Continua

on: 
  push: 
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    #- name: Install SSH Key
    #   uses: shimataro/ssh-key-action@v2
    #   with:
    #     key: ${{ secrets.ssh_key }} 
    #     known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    # - name: Adding Known Hosts
    #   run: ssh-keyscan -H ${{ secrets.ssh_host }} >> /root/known_hosts

    - name: Verificando versao do python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: conectando ssh
      run: |
        ssh root@31.220.48.246
    - name: Instalando dependencias
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fazendo migrate
      run: |
        python3 manage.py migrate
    - name: Rodando server de novo
      run: |
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
