name: Django Integracao Continua

on: 
  push: 
    branches: 
      - main

jobs: 
  first-job:
    name: First-Job
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    
    - name: executing remote ssh commands using password
      uses: ./
      with:
        host: 31.220.48.246
        username: root
        password: Jefersonqueiroga123#
        port: 22
        script: whoami
    # - name: Instalando dependencias
    #   run: |
    #     source venv/bin/activate
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Fazendo migrate
    #   run: |
    #     python3 manage.py migrate
    # - name: Rodando server de novo
    #   run: |
    #     sudo systemctl restart gunicorn
    #     sudo systemctl restart nginx
